const DEFAULT_SCALE = 1;
const MIN_SCALE = 0.1;
const MAX_SCALE = 10;
const DEFAULT_VIEWPOINT_POS = { x: 0, y: 0 };
const ZOOM_FACTOR = 1.06;

export {
  DEFAULT_SCALE,
  MIN_SCALE,
  MAX_SCALE,
  DEFAULT_VIEWPOINT_POS,
  ZOOM_FACTOR,
};
